apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argo.lan.
    metallb.universe.tf/address-pool: lan
  name: argocd-server
spec:
  type: LoadBalancer
